# Configuration of app
# url: url of app

# Specify api url
# api:
  # url:
    # dog_info: dogs/:id
  # other_api:

# mock and cached settings for other app (basically used in development environment)
login_path: /user/login

cached_config:
  master_app_name:  #other app's name
    url: http://localhost:3001
    database:
      test:
        adapter: mysql
        database: eco_apps_auth_test
        username: root
        password: root
        pool: 5
        timeout: 5000

# columns needed for readonly models in test
# readonly_for_test:
#   orders:
#     integer: dog_id, user_id
#     string: description
