# Configuration of app
# url: url of app

# Specify api url
# api:
  # url:
    # dog_info: dogs/:id
  # other_api:

# mock and cached settings for other app (basically used in development environment)
# cached_config:
#   pet:  #other app's name
#     url: http://localhost:3001
#     database:
#       adapter: mysql
#       encoding: utf8
#       database: pet_development
#       host: localhost
#       user: root
#       password: 
#     other app's settings

# columns needed for readonly models in test
# readonly_for_test:
#   orders:
#     integer: dog_id, user_id
#     string: description
